<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AirCOM.RelayLoopTest</RootNamespace>
    <AssemblyName>AirCOM.RelayLoopTest</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AirCOM.Core\AirCOM.Core.csproj" />
    <ProjectReference Include="..\..\src\AirCOM.Server\AirCOM.Server.csproj" />
  </ItemGroup>

</Project>
