<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AirCOM.EchoB</RootNamespace>
    <AssemblyName>AirCOM.EchoB</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirCOM.Core\AirCOM.Core.csproj" />
  </ItemGroup>

</Project>
